In [18]:
import os
import pandas as pd
import numpy as np
import pathlib
import xarray as xr


#### 1- 读取原始文件

In [54]:
read_file_path: str = r'./../data/NMF_TRN_OSTZSS_CSDT_2023052112_168h_SS_maxSurge.txt'
# 读取含中文表头的 tab
with open(read_file_path, 'rb') as f:
    # pandas.core.frame.DataFrame
    data: pd.core.frame.DataFrame = pd.read_csv(f, encoding='gbk', sep='\s+', header=None,
                                                infer_datetime_format=False)
    print('读取成功')


读取成功


In [56]:
data

0      1      2      3      4      5      6      7      8      9    \
0    999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0   
1    999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0   
2    999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0   
3    999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0   
4    999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
215  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0   
216  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0   
217  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0   
218  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0   
219  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0  999.0   

     ...       240       241       242       243       244       245  \
0    ...  999.0000  999.0000  999.0000  999.0000  999.0000  999.0000   
1    ...  999.0000  999.0000  999.0000  999.0000  999.0000  999.0000   
2    ...  999.0000  999.0000  999.0000  999.0000  999.0000  999.0000   
3    ...  999.0000  999.0000  999.0000  999.0000  999.0000  999.0000   
4    ...  999.0000  999.0000  999.0000  999.0000  999.0000  999.0000   
..   ...       ...       ...       ...       ...       ...       ...   
215  ...    0.0158    0.0138    0.0125    0.0114    0.0103    0.0095   
216  ...    0.0123    0.0106    0.0097    0.0088    0.0078    0.0073   
217  ...    0.0084    0.0072    0.0067    0.0062    0.0053    0.0050   
218  ...    0.0043    0.0037    0.0034    0.0032    0.0028    0.0026   
219  ...    0.0000    0.0000    0.0000    0.0000    0.0000    0.0000   

          246       247       248    249  
0    999.0000  999.0000  999.0000  999.0  
1    999.0000  999.0000  999.0000  999.0  
2    999.0000  999.0000  999.0000  999.0  
3    999.0000  999.0000  999.0000  999.0  
4    999.0000  999.0000  999.0000  999.0  
..        ...       ...       ...    ...  
215    0.0077    0.0056    0.0031    0.0  
216    0.0060    0.0044    0.0025    0.0  
217    0.0041    0.0030    0.0017    0.0  
218    0.0021    0.0015    0.0009    0.0  
219    0.0000    0.0000    0.0000    0.0  

[220 rows x 250 columns]

In [62]:
# 定义经纬度数组
# 注意经纬度网格的 长宽 无问题，但是范围有问题
# 250
lon=np.linspace(105,136.25,250)
# 222
lat=np.linspace(12.125,41.875,220)

In [63]:
# ValueError: conflicting sizes for dimension 'lon': length 220 on the data but length 250 on coordinate 'lon'
da = xr.DataArray(data, coords=[lat, lon], dims=['lat', 'lon'])
da


<xarray.DataArray (lat: 220, lon: 250)>
array([[9.99e+02, 9.99e+02, 9.99e+02, ..., 9.99e+02, 9.99e+02, 9.99e+02],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 9.99e+02, 9.99e+02, 9.99e+02],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 9.99e+02, 9.99e+02, 9.99e+02],
       ...,
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 3.00e-03, 1.70e-03, 0.00e+00],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 1.50e-03, 9.00e-04, 0.00e+00],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 0.00e+00, 0.00e+00, 0.00e+00]])
Coordinates:
  * lat      (lat) float64 12.12 12.26 12.4 12.53 ... 41.47 41.6 41.74 41.88
  * lon      (lon) float64 105.0 105.1 105.3 105.4 ... 135.9 136.0 136.1 136.2

In [64]:
da.coords

Coordinates:
  * lat      (lat) float64 12.12 12.26 12.4 12.53 ... 41.47 41.6 41.74 41.88
  * lon      (lon) float64 105.0 105.1 105.3 105.4 ... 135.9 136.0 136.1 136.2

In [65]:
da.dims

('lat', 'lon')

##### step-1 将 coords 修改为经纬度坐标  
网格分辨率为 0.125*0.125  
经纬度范围:[12.125,41.875]
          [100,130]
          [105,0.125*250,136.25]

In [28]:
lon=np.linspace(105,136.25,250)
lat=np.linspace(12.125,41.875,222)

In [33]:
type(lon)

numpy.ndarray

In [34]:
# 需要将lat与lon的ndarray->dataarray
lat_arr=xr.DataArray(lat)
lon_arr=xr.DataArray(lon)

In [41]:
type(lat_arr)

xarray.core.dataarray.DataArray

In [39]:
# lon, lat = np.meshgrid(lon, lat)
coords = {'lon':  lon_arr, 'lat':  lat_arr}

直接针对读取后的 data 声明为 DataArray 并声明坐标

In [46]:
# TypeError: unhashable type: 'numpy.ndarray'
# ValueError: inferring DataArray dimensions from dictionary like ``coords`` is no longer supported. Use an explicit list of ``dims`` instead.
# coords 坐标系不允许通过字典声明，改为dims
da=xr.DataArray(data, dims={'lat': lat_arr, 'lon': lon_arr})

In [51]:
da

<xarray.DataArray (lat: 220, lon: 250)>
array([[9.99e+02, 9.99e+02, 9.99e+02, ..., 9.99e+02, 9.99e+02, 9.99e+02],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 9.99e+02, 9.99e+02, 9.99e+02],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 9.99e+02, 9.99e+02, 9.99e+02],
       ...,
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 3.00e-03, 1.70e-03, 0.00e+00],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 1.50e-03, 9.00e-04, 0.00e+00],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 0.00e+00, 0.00e+00, 0.00e+00]])
Coordinates:
  * lat      (lat) int64 0 1 2 3 4 5 6 7 8 ... 212 213 214 215 216 217 218 219
  * lon      (lon) int64 0 1 2 3 4 5 6 7 8 ... 242 243 244 245 246 247 248 249

In [52]:
lon_arr.count

<bound method ImplementsArrayReduce._reduce_method.<locals>.wrapped_func of <xarray.DataArray (dim_0: 250)>
array([105.        , 105.12550201, 105.25100402, 105.37650602,
       105.50200803, 105.62751004, 105.75301205, 105.87851406,
       106.00401606, 106.12951807, 106.25502008, 106.38052209,
       106.5060241 , 106.6315261 , 106.75702811, 106.88253012,
       107.00803213, 107.13353414, 107.25903614, 107.38453815,
       107.51004016, 107.63554217, 107.76104418, 107.88654618,
       108.01204819, 108.1375502 , 108.26305221, 108.38855422,
       108.51405622, 108.63955823, 108.76506024, 108.89056225,
       109.01606426, 109.14156627, 109.26706827, 109.39257028,
       109.51807229, 109.6435743 , 109.76907631, 109.89457831,
       110.02008032, 110.14558233, 110.27108434, 110.39658635,
       110.52208835, 110.64759036, 110.77309237, 110.89859438,
       111.02409639, 111.14959839, 111.2751004 , 111.40060241,
       111.52610442, 111.65160643, 111.77710843, 111.90261044,
       112

In [50]:
#ValueError: conflicting sizes for dimension 'dim_0': length 250 on 'lon' and length 222 on 'lat'
da.assign_coords(lon=lon_arr,lat=lat_arr)

ValueError: conflicting sizes for dimension 'dim_0': length 250 on 'lon' and length 222 on 'lat'

In [47]:
da

<xarray.DataArray (lat: 220, lon: 250)>
array([[9.99e+02, 9.99e+02, 9.99e+02, ..., 9.99e+02, 9.99e+02, 9.99e+02],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 9.99e+02, 9.99e+02, 9.99e+02],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 9.99e+02, 9.99e+02, 9.99e+02],
       ...,
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 3.00e-03, 1.70e-03, 0.00e+00],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 1.50e-03, 9.00e-04, 0.00e+00],
       [9.99e+02, 9.99e+02, 9.99e+02, ..., 0.00e+00, 0.00e+00, 0.00e+00]])
Coordinates:
  * lat      (lat) int64 0 1 2 3 4 5 6 7 8 ... 212 213 214 215 216 217 218 219
  * lon      (lon) int64 0 1 2 3 4 5 6 7 8 ... 242 243 244 245 246 247 248 249

In [27]:
# ValueError: cannot add coordinates with new dimensions to a DataArray
da.assign_coords(lon=lon,lat=lat)
# 新版本的 xarray中不再使用set_coords改为使用assign_coords
# da = da.set_coords(['lon', 'lat'])

ValueError: cannot add coordinates with new dimensions to a DataArray

In [ ]:
new_da = xr.DataArray(data=da.data, coords={lat: lat, lon: lon})


TypeError: unhashable type: 'numpy.ndarray'

In [ ]:
coords

{'lon': (['lat', 'lon'],
  array([[105.        , 105.12550201, 105.25100402, ..., 135.99899598,
          136.12449799, 136.25      ],
         [105.        , 105.12550201, 105.25100402, ..., 135.99899598,
          136.12449799, 136.25      ],
         [105.        , 105.12550201, 105.25100402, ..., 135.99899598,
          136.12449799, 136.25      ],
         ...,
         [105.        , 105.12550201, 105.25100402, ..., 135.99899598,
          136.12449799, 136.25      ],
         [105.        , 105.12550201, 105.25100402, ..., 135.99899598,
          136.12449799, 136.25      ],
         [105.        , 105.12550201, 105.25100402, ..., 135.99899598,
          136.12449799, 136.25      ]])),
 'lat': (['lat', 'lon'],
  array([[12.125     , 12.125     , 12.125     , ..., 12.125     ,
          12.125     , 12.125     ],
         [12.25961538, 12.25961538, 12.25961538, ..., 12.25961538,
          12.25961538, 12.25961538],
         [12.39423077, 12.39423077, 12.39423077, ..., 12.39423077

In [ ]:
da.to_dataset

ValueError: cannot convert an unnamed DataArray to a DataFrame: use the ``name`` parameter

In [66]:
# 尝试将 DataFrame转换为 DataSet
type(data)
ds=xr.Dataset.from_dataframe(data)

### 将`Dataarray`转换为`Dataset` 

In [71]:
ds = xr.Dataset({'max_surge': da})


In [72]:
ds

<xarray.Dataset>
Dimensions:    (lat: 220, lon: 250)
Coordinates:
  * lat        (lat) float64 12.12 12.26 12.4 12.53 ... 41.47 41.6 41.74 41.88
  * lon        (lon) float64 105.0 105.1 105.3 105.4 ... 135.9 136.0 136.1 136.2
Data variables:
    max_surge  (lat, lon) float64 999.0 999.0 999.0 999.0 ... 0.0 0.0 0.0 0.0

#### 将`Dataset`存储为`nc`

In [73]:
ds.to_netcdf('max_surge.nc')

In [ ]:
ds_2d=ds.unstack().transpose()

In [ ]:
ds_2d

<xarray.Dataset>
Dimensions:  (index: 220)
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 ... 212 213 214 215 216 217 218 219
Data variables: (12/250)
    0        (index) float64 999.0 999.0 999.0 999.0 ... 999.0 999.0 999.0 999.0
    1        (index) float64 999.0 999.0 999.0 999.0 ... 999.0 999.0 999.0 999.0
    2        (index) float64 999.0 999.0 999.0 999.0 ... 999.0 999.0 999.0 999.0
    3        (index) float64 999.0 999.0 999.0 999.0 ... 999.0 999.0 999.0 999.0
    4        (index) float64 999.0 999.0 999.0 999.0 ... 999.0 999.0 999.0 999.0
    5        (index) float64 999.0 999.0 999.0 999.0 ... 999.0 999.0 999.0 999.0
    ...       ...
    244      (index) float64 999.0 999.0 999.0 999.0 ... 0.0053 0.0028 0.0
    245      (index) float64 999.0 999.0 999.0 999.0 ... 0.0073 0.005 0.0026 0.0
    246      (index) float64 999.0 999.0 999.0 999.0 ... 0.006 0.0041 0.0021 0.0
    247      (index) float64 999.0 999.0 999.0 999.0 ... 0.0044 0.003 0.0015 0.0
    248      (index) float64 999.0 999.0 999.0 999.0 ... 0.0017 0.0009 0.0
    249      (index) float64 999.0 999.0 999.0 999.0 999.0 ... 0.0 0.0 0.0 0.0

### 2- 使用xarray直接读取指定文件

In [ ]:
ds=xr.open_dataset(read_file_path,delim_whitespace=True)
ds

TypeError: open_dataset() got an unexpected keyword argument 'delim_whitespace'